export const FETCH_ALBUMS_REQUEST = 'FETCH_ALBUMS_REQUEST';
export const FETCH_ALBUMS_REQUEST_SUCCESS = 'FETCH_ALBUMS_REQUEST_SUCCESS';
export const FETCH_ALBUMS_REQUEST_FAILURE = 'FETCH_ALBUMS_REQUEST_FAILURE';